/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  1: {
    TrustMAttest: {
      address: "0xa2b53f0c5c700e42020d91a1c0e481389da1e197",
      abi: [
        {
          type: "function",
          name: "CA_X",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CA_Y",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "attest",
          inputs: [
            {
              name: "cert",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "tbsStart",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "tbsLen",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "pkOffset",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "r",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "s",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "x",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "y",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "attested",
          inputs: [
            {
              name: "keyId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isChipSignature",
          inputs: [
            {
              name: "x",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "y",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "hash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "r",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "s",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "keyIdOf",
          inputs: [
            {
              name: "x",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "y",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "lowS",
          inputs: [
            {
              name: "s",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "event",
          name: "Attested",
          inputs: [
            {
              name: "keyId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "x",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "y",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "BadKeyOffset",
          inputs: [],
        },
        {
          type: "error",
          name: "CertNotSignedByCA",
          inputs: [],
        },
        {
          type: "error",
          name: "NotP256Key",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 26001790,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
